import test from 'node:test';
import assert from 'node:assert/strict';
import {D,uprightVolume,tiltedVolume,volumeAtHeight,liquidHeight,displacedTipVolume,toWorld,toLocal,instrumentClearance,sweptClearance,capillaryLength,moveTime,defaultFixture} from '../src/model/geometry';
import {scenario,worldFromScenario,policy} from '../src/model/scenarios';
import {runSimulation} from '../src/model/simulation';
import {refract,renderObservation,extractFeatures} from '../src/model/optics';
import {initialBelief,updateBelief} from '../src/model/belief';
import {validateTrace} from '../src/model/validation';
import {stream} from '../src/model/math';
test('upright closed form agrees with independent fine midpoint integration',()=>{for(const h of [1,5,11,20,32]){const n=50000,dz=h/n;let v=0;for(let i=0;i<n;i++){const z=(i+.5)*dz,r=z<11?.55+(4.3-.55)*z/11:4.3;v+=Math.PI*r*r*dz;}assert.ok(Math.abs(uprightVolume(h)-v)<1e-5);}});
test('tilted quadrature converges and inverse volume closes',()=>{for(const tilt of [0,5,10]as const)for(const volume of [65,150,400,850,1400]){const h=liquidHeight(volume,tilt);assert.ok(Math.abs(volumeAtHeight(h,tilt)-volume)<.001);assert.ok(Math.abs(tiltedVolume(h,tilt,2048)-volume)<.15);}});
test('immersed tip raises surface while conserving liquid volume',()=>{const tip:[number,number,number]=[0,0,5],volume=600,h=liquidHeight(volume,0,tip);assert.ok(h>liquidHeight(volume,0));assert.ok(Math.abs(volumeAtHeight(h,0)-displacedTipVolume(h,tip)-volume)<.001);});
test('rigid transforms invert for all supported inclinations',()=>{for(const tilt of [0,5,10]){const a=toLocal(toWorld([2,-1,17],tilt,[.5,-.3,0]),tilt,[.5,-.3,0]);assert.ok(a.every((v,i)=>Math.abs(v-[2,-1,17][i])<1e-10));}});
test('swept check rejects a wall crossing with clear endpoints',()=>{const w=worldFromScenario(scenario('known'));w.pose=[0,0,0];assert.ok(instrumentClearance([0,0,40],w)>0);assert.ok(instrumentClearance([15,0,40],w)>0);assert.ok(sweptClearance([15,0,20],[0,0,20],w)<0);});
test('shaft and mouth fit are checked, not just aperture position',()=>{const w=worldFromScenario(scenario('known'));w.pose=[0,0,0];w.tilt=10;assert.ok(instrumentClearance(toWorld([2.3,0,4],10),w)<0);});
test('capillary length and kinematic timing are dimensionally consistent',()=>{assert.ok(capillaryLength()>1.7&&capillaryLength()<1.9);assert.equal(moveTime([0,0,0],[0,0,0]),0);assert.ok(moveTime([0,0,0],[0,0,30])>30/D.stage.maxVelocity);});
test('Snell law, normal incidence, and total internal reflection',()=>{const d=refract([0,0,-1],[0,0,1],1,1.36)!;assert.deepEqual(d,[0,0,-1]);const theta=.5,r=refract([Math.sin(theta),0,-Math.cos(theta)],[0,0,1],1,1.49)!;assert.ok(Math.abs(r[0]-Math.sin(theta)/1.49)<1e-12);assert.equal(refract([.95,0,-Math.sqrt(1-.95**2)],[0,0,1],1.49,1),null);});
test('pixel-derived surface tracks two different true volumes',()=>{const s=scenario('known'),w=worldFromScenario(s);for(const v of [350,850]){w.volume=v;const f=extractFeatures(renderObservation(w,'side',s.seed,0,`v${v}`));assert.notEqual(f.level,null);assert.ok(Math.abs(f.level!-liquidHeight(v,0))<1);}});
test('duplicate correlated exposure cannot sharpen the posterior twice',()=>{const s=scenario('known'),w=worldFromScenario(s),packet=renderObservation(w,'side',s.seed,0,'same');const b=updateBelief(initialBelief(s),packet,s).belief;assert.deepEqual(updateBelief(b,packet,s).belief,b);});
test('missing context remains unresolved and stops before movement',()=>{const t=runSimulation(scenario('missing'),policy('belief'));assert.equal(t.result.status,'stopped');assert.equal(t.result.removed,0);assert.equal(t.result.observations,2);assert.ok(!t.events.some(e=>e.action.kind==='move'));});
test('run conserves wash mass and retains replayable provenance',()=>{const t=runSimulation(scenario('known'),policy('belief'));assert.ok(Math.abs(t.initial.volume-t.result.remaining-t.result.removed)<1e-8);assert.ok(t.result.removed>500);assert.deepEqual(t.result.violations,[]);assert.deepEqual(validateTrace(t).events,t.events);assert.deepEqual(runSimulation(scenario('known'),policy('belief')),t);});
test('named random streams separate observations from actuation',()=>{const a=stream(12,'actuation'),b=stream(12,'actuation'),sensor=stream(12,'sensor');sensor();sensor();assert.equal(a(),b());});
test('trace import rejects malformed and oversized numeric state',()=>{assert.throws(()=>validateTrace({version:2}));const t=runSimulation(scenario('missing'),policy('belief'));t.events[0].tip[0]=Infinity;assert.throws(()=>validateTrace(t));});
