import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {D,innerRadius,liquidHeight,pelletPosition,toWorld} from '../model/geometry';
import type {WorldState,Vec3} from '../model/types';
interface Props {world:WorldState;tip:Vec3;cutaway:boolean;showBelief:boolean;reset:number;active:boolean;}
const point=(p:Vec3)=>new THREE.Vector3(p[0],p[2],-p[1]);
function fluidMesh(height:number,tilt:number){const positions:number[]=[],indices:number[]=[],n=72,m=40,angle=tilt*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle);for(let j=0;j<=m;j++){for(let i=0;i<=n;i++){const a=2*Math.PI*i/n;let surface=(height+s*D.tube.innerRadius*Math.cos(a))/c;if(surface<D.tube.coneHeight)surface=(height+s*D.tube.innerBaseRadius*Math.cos(a))/(c-s*(D.tube.innerRadius-D.tube.innerBaseRadius)/D.tube.coneHeight*Math.cos(a));const z=surface*j/m,r=innerRadius(z)*.98;positions.push(r*Math.cos(a),z,-r*Math.sin(a));}}for(let j=0;j<m;j++)for(let i=0;i<n;i++){const a=j*(n+1)+i;indices.push(a,a+n+1,a+1,a+1,a+n+1,a+n+2);}const center=positions.length/3;positions.push(0,height/c,0);for(let i=0;i<n;i++)indices.push(center,m*(n+1)+i,m*(n+1)+i+1);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setIndex(indices);g.computeVertexNormals();return g;}
export function Workbench(props:Props){const mount=useRef<HTMLDivElement>(null),api=useRef<{update:(p:Props)=>void;reset:()=>void}|null>(null),[error,setError]=useState(false);const latest=useRef(props);latest.current=props;
 useEffect(()=>{const el=mount.current!;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{setError(true);return;}renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.86;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(30,1,.1,600);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.minDistance=60;controls.maxDistance=210;controls.maxPolarAngle=Math.PI*.49;controls.target.set(0,15,0);const reset=()=>{camera.position.set(67,64,95);controls.target.set(0,15,0);controls.update();request();};
 const pmrem=new THREE.PMREMGenerator(renderer),environment=pmrem.fromScene(new RoomEnvironment(),.04);scene.environment=environment.texture;
 scene.add(new THREE.HemisphereLight(0xf7f7ed,0x67796d,.8));const light=new THREE.DirectionalLight(0xfff7e5,2.5);light.position.set(-30,75,50);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-65,right:65,top:70,bottom:-60,near:1,far:240});light.shadow.bias=-.0005;light.shadow.normalBias=.035;scene.add(light);const fill=new THREE.DirectionalLight(0xd5e5ef,1.2);fill.position.set(50,30,-40);scene.add(fill);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(700,700),new THREE.ShadowMaterial({opacity:.16}));ground.rotation.x=-Math.PI/2;ground.position.y=-11.1;ground.receiveShadow=true;scene.add(ground);
 const stage=new THREE.Group(),assembly=new THREE.Group(),tubeGroup=new THREE.Group(),tipGroup=new THREE.Group();assembly.add(tubeGroup);scene.add(stage,assembly,tipGroup);
 const fluid=new THREE.Mesh(fluidMesh(20,0),new THREE.MeshPhysicalMaterial({color:0xa9b9a6,roughness:.16,metalness:.02,transparent:true,opacity:.68,side:THREE.DoubleSide,depthWrite:false}));tubeGroup.add(fluid);
 const meniscus=new THREE.Mesh(new THREE.CircleGeometry(4.3,80),new THREE.MeshPhysicalMaterial({color:0xc0d0b8,roughness:.12,metalness:.08,transparent:true,opacity:.9,side:THREE.DoubleSide}));meniscus.rotation.x=-Math.PI/2;tubeGroup.add(meniscus);
 const pellet=new THREE.Mesh(new THREE.SphereGeometry(.65,24,16),new THREE.MeshStandardMaterial({color:0xe0d7bc,roughness:.95}));pellet.scale.set(1,.55,1);scene.add(pellet);
 const protectedRing=new THREE.Mesh(new THREE.TorusGeometry(2.45,.045,8,80),new THREE.MeshBasicMaterial({color:0xc18b43,transparent:true,opacity:.85,depthTest:false}));protectedRing.rotation.x=-Math.PI/2;scene.add(protectedRing);
 const uncertainty=new THREE.Mesh(new THREE.SphereGeometry(2.45,32,20),new THREE.MeshBasicMaterial({color:0xd19b50,transparent:true,opacity:.06,depthWrite:false}));scene.add(uncertainty);
 const pathMaterial=new THREE.LineDashedMaterial({color:0x7b8f80,dashSize:.65,gapSize:.45,transparent:true,opacity:.75});const path=new THREE.Line(new THREE.BufferGeometry().setFromPoints([point([0,-1.35,4]),point([0,-1.35,41])]),pathMaterial);path.computeLineDistances();scene.add(path);
 const carriage=new THREE.Mesh(new THREE.BoxGeometry(23,6,9),new THREE.MeshStandardMaterial({color:0xa8afa7,metalness:.7,roughness:.3}));carriage.position.set(11,90,-24);scene.add(carriage);
 const loader=new GLTFLoader();let front:THREE.Object3D|undefined,disposed=false;const loaded:THREE.Object3D[]=[];
 async function load(name:string,parent:THREE.Group){try{const gltf=await loader.loadAsync(`/assets/${name}.glb`);if(disposed)return;gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material];for(const mat of mats){if(mat instanceof THREE.MeshStandardMaterial){mat.envMapIntensity=.55;if(mat.name.startsWith('Polypropylene')){const p=mat as THREE.MeshPhysicalMaterial;p.transmission=.18;p.roughness=.3;p.color.set(0xc4cec3);}}}}if(o.name==='tube_front')front=o;});parent.add(gltf.scene);loaded.push(gltf.scene);update(latest.current);request();}catch(e){console.error('Asset load failed',e);setError(true);}}
 void load('workcell',stage);void load('holder',assembly);void load('tube',tubeGroup);void load('tip',tipGroup);
 let lastVolume=-1,raf=0;function request(){if(!raf&&!document.hidden)raf=requestAnimationFrame(()=>{raf=0;renderer.render(scene,camera);});}
 function update(p:Props){assembly.rotation.z=-p.world.tilt*Math.PI/180;tubeGroup.position.set(0,0,0);assembly.position.copy(point(p.world.pose));tipGroup.position.copy(point(p.tip));carriage.position.y=p.tip[2]+59;if(front)front.visible=!p.cutaway;
  if(Math.abs(lastVolume-p.world.volume)>.1){lastVolume=p.world.volume;const h=liquidHeight(p.world.volume,p.world.tilt,p.tip);fluid.geometry.dispose();fluid.geometry=fluidMesh(h,p.world.tilt);meniscus.visible=p.world.tilt===0;meniscus.position.y=h;meniscus.scale.setScalar(innerRadius(h)/4.3);}
  const pp=point(pelletPosition(p.world));pellet.position.copy(pp);protectedRing.position.copy(pp);uncertainty.position.copy(pp);protectedRing.visible=p.showBelief;uncertainty.visible=p.showBelief;path.visible=p.showBelief;request();}
 const resize=new ResizeObserver(()=>{const {width,height}=el.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();request();});resize.observe(el);controls.addEventListener('change',request);document.addEventListener('visibilitychange',request);api.current={update,reset};reset();
 return()=>{disposed=true;resize.disconnect();controls.dispose();cancelAnimationFrame(raf);document.removeEventListener('visibilitychange',request);scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose());}});environment.texture.dispose();pmrem.dispose();renderer.dispose();el.removeChild(renderer.domElement);api.current=null;};
 },[]);
 useEffect(()=>{api.current?.update(props);},[props.world,props.tip,props.cutaway,props.showBelief,props.active]);useEffect(()=>{api.current?.reset();},[props.reset]);
 return <div className="scene-canvas" ref={mount} aria-label="Interactive 3D workcell. Drag to orbit, scroll to zoom.">{error&&<div className="scene-error">The 3D view could not load. You can still inspect the run and export its evidence.</div>}</div>;
}
