import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowRight,ArrowUpRight,Box,Check,ChevronDown,ChevronRight,ChevronLeft,Compass,Download,Eye,Focus,Github,Info,Layers,LoaderCircle,Maximize2,Pause,Play,RotateCcw,ScanLine,Settings2,ShieldCheck,SlidersHorizontal,Square,Upload,X} from 'lucide-react';
import {Workbench} from './scene/Workbench';
import {CameraFrame} from './components/CameraFrame';
import {SCENARIOS,CONTROLLERS,scenario,policy,worldFromScenario} from './model/scenarios';
import {D,capillaryLength,MODEL_VERSION} from './model/geometry';
import type {ScenarioId,ControllerId,RunTrace,ObservationPacket,Tilt,Vec3,ExperimentReport} from './model/types';
type Mode='run'|'investigate'|'design';
function save(name:string,value:unknown,type='application/json'){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
const format=(n:number)=>Math.round(n).toLocaleString();
export default function App(){
 const [mode,setMode]=useState<Mode>('run'),[scenarioId,setScenario]=useState<ScenarioId>('known'),[controller,setController]=useState<ControllerId>('belief'),[seed,setSeed]=useState(1847),[tilt,setTilt]=useState<Tilt>(0),[indexed,setIndexed]=useState(true),[cutaway,setCutaway]=useState(true),[showBelief,setShowBelief]=useState(true),[reset,setReset]=useState(0),[inspector,setInspector]=useState(false),[about,setAbout]=useState(false),[trace,setTrace]=useState<RunTrace|null>(null),[packets,setPackets]=useState<ObservationPacket[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[speed,setSpeed]=useState(2),[error,setError]=useState(''),[report,setReport]=useState<ExperimentReport|null>(null),[exporting,setExporting]=useState(false);
 const worker=useRef<Worker|null>(null),fileInput=useRef<HTMLInputElement>(null);const config=useMemo(()=>{const s=scenario(scenarioId,seed);s.fixture.tilt=tilt;s.fixture.indexed=indexed;return s;},[scenarioId,seed,tilt,indexed]);
 const initial=useMemo(()=>worldFromScenario(config),[config]);
 function createWorker(){const w=new Worker(new URL('./workers/simulation.worker.ts',import.meta.url),{type:'module'});w.onmessage=e=>{const m=e.data;if(m.type==='progress')setProgress(m.progress);if(m.type==='preview')setPackets(m.packets);if(m.type==='done'){setTrace(m.trace);setPackets(m.packets);setBusy(false);setTime(0);setPlaying(true);}if(m.type==='error'){setError(m.message);setBusy(false);}};w.onerror=e=>{setError(e.message);setBusy(false);};worker.current=w;return w;}
 useEffect(()=>{const w=createWorker();w.postMessage({type:'preview',scenario:config,policy:policy(controller)});setTrace(null);setTime(0);setPlaying(false);setBusy(false);return()=>w.terminate();},[config]);
 useEffect(()=>{fetch('/data/experiment.json').then(r=>r.ok?r.json():null).then(setReport).catch(()=>{});},[]);
 useEffect(()=>{if(!playing||!trace||document.hidden)return;let frame=0,last=performance.now();function tick(now:number){const dt=Math.min(.1,(now-last)/1000);last=now;setTime(t=>{const next=t+dt*speed;if(next>=trace!.result.seconds){setPlaying(false);return trace!.result.seconds;}return next;});frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,trace,speed]);
 useEffect(()=>{const hidden=()=>{if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden);},[]);
 const currentIndex=trace?Math.max(0,trace.events.findLastIndex(e=>e.t<=time)):0,current=trace?.events[currentIndex],previous=trace?.events[Math.max(0,currentIndex-1)];
 const u=current?Math.min(1,Math.max(0,(time-current.t)/(current.duration||1))):0;
 const visibleVolume=current?(current.action.kind==='aspirate'?(previous?.volume??initial.volume)+(current.volume-(previous?.volume??initial.volume))*u:current.volume):initial.volume;
 const tip:Vec3=current?(current.action.kind==='move'?current.tip.map((v,i)=>(previous?.tip[i]??[0,-1.5,42][i])+(v-(previous?.tip[i]??[0,-1.5,42][i]))*u) as Vec3:current.tip):[0,-1.5,42];
 const visibleWorld=useMemo(()=>({...trace?.initial??initial,volume:visibleVolume,fixture:config.fixture,tilt}),[trace,initial,visibleVolume,config.fixture,tilt]);
 const finished=!!trace&&time>=trace.result.seconds;const stateLabel=busy?'Computing':playing?'Executing':finished?'Run complete':trace?'Paused':'Ready to run';
 const activePacket=(view:'side'|'overhead')=>packets.filter(p=>p.calibration.view===view&&p.t<=time).at(-1)??packets.find(p=>p.calibration.view===view);
 const sInfo=SCENARIOS.find(s=>s.id===scenarioId)!;
 const run=()=>{setError('');setBusy(true);setProgress(0);setPlaying(false);worker.current?.postMessage({type:'run',scenario:config,policy:policy(controller)});};
 function cancel(){worker.current?.terminate();createWorker();setBusy(false);setProgress(0);}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,select,textarea,button'))return;if(e.code==='Space'){e.preventDefault();trace?setPlaying(v=>!v):run();}if(e.key==='Escape'){setAbout(false);setInspector(false);}if(e.key.toLowerCase()==='r')setReset(r=>r+1);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[trace,config,controller]);
 function exportCSV(){if(!trace)return;save(`${trace.id}.csv`,'time_s,action,remaining_uL,aspirated_uL,clearance_mm,violations\n'+trace.events.map(e=>[e.t.toFixed(3),e.action.kind,e.volume.toFixed(3),e.aspirated.toFixed(3),e.clearance.toFixed(3),e.violations.join(';')].join(',')).join('\n'),'text/csv');}
 async function exportCAD(){setExporting(true);try{const {exportFixture}=await import('./cad/fixture');const result=await exportFixture(config.fixture);save('tacit-holder-dimensions.json',result.notes);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([result.stl],{type:'model/stl'}));a.download=`tacit-holder-${tilt}deg.stl`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}catch(e){setError(String(e));}finally{setExporting(false);}}
 async function importTrace(file:File){try{if(file.size>5_000_000)throw Error('Trace exceeds the 5 MB limit.');const input=JSON.parse(await file.text());const {validateTrace}=await import('./model/validation');const t=validateTrace(input);setPlaying(false);setScenario(t.scenario.id);setSeed(t.scenario.seed);setTilt(t.scenario.fixture.tilt);setController(t.policy.controller);setTimeout(()=>{setTrace(t);setTime(t.result.seconds);setPackets([]);setMode('investigate');},100);}catch(e){setError(e instanceof Error?e.message:'Could not import trace.');}}
 return <div className="app-shell">
  <header className="header"><a className="brand" href="/" aria-label="TACIT home"><span className="brand-mark"><i/><i/><i/></span><span>TACIT<span className="brand-period">.</span></span><span className="brand-description">PHYSICAL REASONING<br/>WORKBENCH / 01</span></a><nav className="mode-nav" aria-label="Workbench mode">{(['run','investigate','design'] as Mode[]).map((m,i)=><button key={m} className={mode===m?'selected':''} onClick={()=>setMode(m)}><span className="nav-number">0{i+1}</span>{m[0].toUpperCase()+m.slice(1)}</button>)}</nav><div className="header-right"><span className="build-label"><span className="signal-dot"/>RESEARCH BUILD</span><button className="icon-button" aria-label="About TACIT" onClick={()=>setAbout(true)}><Info size={18}/></button></div></header>
  <main><div className="page-heading"><div><div className="eyebrow">RNA ISOLATION <span>/</span> THE EXECUTION LAYER</div><h1>Remove the wash. <span>Preserve the pellet.</span></h1></div><button className="text-button" onClick={()=>setAbout(true)}>Why this task <ArrowUpRight size={15}/></button></div>
  <div className="workbench-layout"><section className="viewport" aria-label="Physical workcell"><div className="viewport-top"><div className="viewport-id"><span className="small-cross">+</span><span className="mono">WORKCELL A—01</span><span className="viewport-divider"/><span className="viewport-subtitle">{cutaway?'Section view':'Material view'}</span></div><div className="viewport-tools"><button className={cutaway?'on':''} aria-label="Toggle tube cutaway" title="Toggle tube cutaway" onClick={()=>setCutaway(v=>!v)}><Layers size={16}/></button><button className={showBelief?'on':''} aria-label="Toggle uncertainty overlay" title="Toggle uncertainty overlay" onClick={()=>setShowBelief(v=>!v)}><ScanLine size={16}/></button><button aria-label="Reset camera" title="Reset camera · R" onClick={()=>setReset(r=>r+1)}><Focus size={17}/></button></div></div>
   <Workbench world={visibleWorld} tip={tip} cutaway={cutaway} showBelief={showBelief} reset={reset} active={playing}/>
   <div className="scene-side-label"><span className="vertical-rule"/><span className="mono">NOMINAL 1.5 mL / PP</span></div>
   <div className="scene-annotation"><span className="annotation-line"/><div><span className="annotation-dot"/>PELLET EXCLUSION ENVELOPE<small>{showBelief?'Uncertainty shown at physical scale':'Overlay hidden'}</small></div></div>
   <div className="viewport-bottom"><div className="orientation"><Compass size={22}/><span>Drag to orbit <b>·</b> Scroll to zoom</span></div><span className="model-label">EXPLANATORY 3D <span>≠</span> CAMERA EVIDENCE</span></div>
   <div className="volume-readout"><span className="eyebrow">WASH REMAINING</span><div>{format(visibleVolume)}<span>µL</span></div><div className="volume-meter"><i style={{width:`${Math.min(100,visibleVolume/initial.volume*100)}%`}}/></div><small>{trace?`${format(initial.volume-visibleVolume)} µL removed`:'Initial liquid volume · simulated'}</small></div>
  </section>
  <aside className="control-panel">
   <div className="panel-header"><span className="eyebrow">{mode==='design'?'CONFIGURATION':mode==='investigate'?'EXECUTION EVIDENCE':'PROCEDURE'}</span><span className={`status ${playing?'live':''}`}><i/>{stateLabel}</span></div>
   {mode==='run'&&<><div className="scenario-select"><label htmlFor="scenario">SCENARIO</label><div className="select-wrap"><select id="scenario" value={scenarioId} onChange={e=>{setScenario(e.target.value as ScenarioId);setIndexed(e.target.value!=='missing');}}>{SCENARIOS.map(s=><option key={s.id} value={s.id}>{s.number} / {s.name}</option>)}</select><ChevronDown size={16}/></div><p>{sInfo.description}</p></div><div className="controller-field"><label htmlFor="controller">CONTROLLER</label><div className="select-wrap"><select id="controller" value={controller} onChange={e=>{setController(e.target.value as ControllerId);setTrace(null);setPlaying(false);setTime(0);}}>{CONTROLLERS.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select><ChevronDown size={16}/></div><div className="controller-hint"><ShieldCheck size={16}/><span>{CONTROLLERS.find(c=>c.id===controller)!.description}</span></div></div><div className="run-controls"><button className="primary-button" onClick={busy?cancel:trace&&!finished?()=>setPlaying(p=>!p):run}>{busy?<><Square size={15}/>Cancel computation <span>{Math.round(progress*100)}%</span></>:playing?<><Pause size={17}/>Pause execution <span>SPACE</span></>:trace&&!finished?<><Play size={17}/>Resume execution <span>SPACE</span></>:<><Play size={17} fill="currentColor"/>{trace?'Run again':'Run procedure'}<span>SPACE</span></>}</button></div><div className="thin-divider"/><div className="section-label"><span>OBSERVATION CHANNELS</span><span className="mono">02</span></div><div className="camera-grid"><CameraFrame label="SIDE" packet={activePacket('side')} active={current?.observation?.view==='side'}/><CameraFrame label="OVERHEAD" packet={activePacket('overhead')} active={current?.observation?.view==='overhead'}/></div><button className="inspector-trigger" onClick={()=>setInspector(v=>!v)}><SlidersHorizontal size={15}/>Instrument settings<ChevronDown size={15} className={inspector?'rotated':''}/></button></>}
   {mode==='investigate'&&<><div className="investigate-intro"><h2>Every decision has a reason.</h2><p>{trace?'Follow the evidence from observation to action. Select a moment on the timeline.':'Run a procedure to inspect its synchronized actions, camera evidence, and uncertainty.'}</p></div>{trace?<><div className="decision-card"><div className="eyebrow">DECISION {String(currentIndex+1).padStart(2,'0')} <span>/ {trace.events.length}</span></div><h3>{current?.action.kind==='stop'?'A deliberate stopping point':current?.action.kind==='observe'?'Acquire evidence':current?.action.kind==='move'?'Position the instrument':'Withdraw wash liquid'}</h3><p>{current?.reason}</p></div><div className="evidence-values"><div><span>Liquid estimate · 95% interval</span><strong>{current?.belief.volume.map(format).join(' – ')} <small>µL</small></strong></div><div><span>Pellet orientation</span><strong>{current?.belief.pelletKnown?'History / evidence available':'Unresolved'}</strong></div><div><span>Recorded constraint violations</span><strong className={trace.result.violations.length?'warning-text':''}>{trace.result.violations.length?trace.result.violations.join(', '):'None in this run'}</strong></div></div><div className="camera-grid"><CameraFrame label="SIDE" packet={activePacket('side')}/><CameraFrame label="OVERHEAD" packet={activePacket('overhead')}/></div><div className="export-buttons"><button className="secondary-button" onClick={()=>save(`${trace.id}.json`,trace)}><Download size={15}/>Trace JSON</button><button className="secondary-button" onClick={exportCSV}><Download size={15}/>CSV</button></div></>:<button className="primary-button" onClick={()=>{setMode('run');run();}}><Play size={16}/>Run a procedure<ArrowRight size={16}/></button>}<button className="inspector-trigger" onClick={()=>fileInput.current?.click()}><Upload size={15}/>Import a saved trace<ChevronRight size={15}/></button></>}
   {mode==='design'&&<><div className="investigate-intro"><h2>Design the conditions<br/>for a better action.</h2><p>The holder changes access and observability. Its benefit must survive the physical constraints.</p></div><div className="design-field"><label>HOLDER INCLINATION</label><div className="tilt-selector">{([0,5,10] as Tilt[]).map(v=><button key={v} onClick={()=>setTilt(v)} className={tilt===v?'selected':''}><span className="tilt-glyph" style={{transform:`rotate(${v}deg)`}}/>{v}°</button>)}</div></div><label className="toggle-field"><span><b>Orientation index</b><small>Preserves known handling history</small></span><input type="checkbox" checked={indexed} onChange={e=>setIndexed(e.target.checked)}/><span className="toggle"/></label><div className="design-note"><Info size={15}/><p>A keyed holder cannot recover a lost centrifugation record. Seating accuracy is an assumption until physically measured.</p></div><div className="dimension-row"><span>Seat clearance</span><strong>{config.fixture.clearance.toFixed(2)} mm</strong></div><div className="dimension-row"><span>Nominal footprint</span><strong>34 × 28 mm</strong></div><div className="dimension-row"><span>Camera window</span><strong>{config.fixture.window} mm</strong></div><div className="design-actions"><button className="primary-button" onClick={()=>{setMode('run');run();}}><Play size={16}/>Test this configuration<ArrowRight size={16}/></button><button className="secondary-button" disabled={exporting} onClick={exportCAD}>{exporting?<LoaderCircle size={15} className="spin"/>:<Box size={15}/>}Export holder STL + dimensions</button></div><p className="fine-print">Untested bench fixture. Nominal geometry. Verify fit before fabrication.</p></>}
   {inspector&&<div className="settings-drawer"><label>REPRODUCIBLE SEED<input type="number" value={seed} onChange={e=>setSeed(Math.max(1,Number(e.target.value)||1))}/></label><div><span>Withdrawal rate</span><b>{D.operating.flowRate} µL/s</b></div><div><span>Settling interval</span><b>{D.operating.settleTime} s</b></div><div><span>Capillary length</span><b>{capillaryLength().toFixed(2)} mm</b></div><small>Model parameters are research assumptions, not a validated laboratory procedure.</small></div>}
  </aside></div>
  <section className="timeline" aria-label="Execution timeline"><div className="timeline-heading"><div><span className="eyebrow">EXECUTION TIMELINE</span><span className="timeline-subtitle">{trace?`${trace.events.length} actions · seed ${trace.scenario.seed}`:'An instruction becomes a sequence of physical decisions.'}</span></div><div className="playback-tools"><button className="icon-button" aria-label="Restart replay" disabled={!trace} onClick={()=>{setTime(0);setPlaying(false);}}><RotateCcw size={14}/></button><button className="speed-button mono" onClick={()=>setSpeed(v=>v===1?2:v===2?4:1)}>{speed}×</button><span className="timeline-clock mono">{time.toFixed(1)} <span>/ {trace?.result.seconds.toFixed(1)??'—'} s</span></span></div></div><div className="timeline-track"><div className="timeline-rail">{trace?trace.events.filter(e=>e.duration>0).map(e=><button key={e.index} title={`${e.action.kind} · ${e.t.toFixed(1)} s`} className={`timeline-segment action-${e.action.kind} ${e.t<=time?'elapsed':''}`} style={{left:`${100*e.t/trace.result.seconds}%`,width:`${100*e.duration/trace.result.seconds}%`}} onClick={()=>{setTime(e.t);setPlaying(false);}}/>):<div className="empty-track"><i/><i/><i/><i/><i/><i/></div>}{trace&&<div className="timeline-playhead" style={{left:`${100*time/(trace.result.seconds||1)}%`}}/>}</div><input aria-label="Scrub execution time" type="range" min={0} max={trace?.result.seconds||1} step={.01} value={time} disabled={!trace} onChange={e=>{setPlaying(false);setTime(Number(e.target.value));}}/></div><div className="timeline-legend"><span><i className="legend-observe"/>Observe</span><span><i className="legend-move"/>Move</span><span><i className="legend-aspirate"/>Aspirate</span><span className="timeline-outcome">{finished?<><span className="signal-dot"/>{trace?.result.status==='completed'?'Bulk-removal target reached':trace?.result.status==='violated'?'Constraint violation recorded':'Stopped within the declared model'}</>:<><span className="tiny-cross">+</span> Observations, motion, and volume share one clock</>}</span></div></section>
  {mode==='design'&&<section className="benchmark"><div><div className="eyebrow">HELD-OUT EVIDENCE</div><h2>Compare the tradeoffs.</h2><p>Residual wash and execution time are reported alongside constraint violations.</p></div>{report?<div className="benchmark-table"><div className="benchmark-row table-head"><span>Controller</span><span>Residual</span><span>Time</span><span>Violations</span></div>{report.summaries.map(s=><div className="benchmark-row" key={s.controller}><span>{CONTROLLERS.find(c=>c.id===s.controller)?.short}</span><strong>{s.meanRemaining.toFixed(0)} µL</strong><span>{s.meanSeconds.toFixed(1)} s</span><span>{(s.violationRate*100).toFixed(1)}% <small>n={s.n}</small></span></div>)}<button className="text-button" onClick={()=>save('tacit-experiment.json',report)}>Download methods and results<ArrowDownToLine size={14}/></button></div>:<div className="benchmark-pending"><span className="mono">EVALUATION PENDING</span><p>Measured results will appear after the versioned experiment suite has completed. No estimated uplift is shown.</p></div>}</section>}
  <footer><span><b>TACIT</b> <span className="footer-dot">/</span> An independent project by Raaif Bokhari</span><div><button onClick={()=>setAbout(true)}>Model & methods<ArrowUpRight size={13}/></button><a href="https://github.com/raaaaaif/tacit" target="_blank" rel="noreferrer">Source<Github size={14}/></a><span className="mono">v0.1</span></div></footer>
  </main>
  <input className="sr-only" type="file" accept=".json" ref={fileInput} onChange={e=>{if(e.target.files?.[0])void importTrace(e.target.files[0]);e.target.value='';}}/>
  {error&&<div className="error-toast" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
  {about&&<div className="modal-backdrop" onClick={()=>setAbout(false)}><section className="about-modal" role="dialog" aria-modal="true" aria-labelledby="about-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="Close about dialog" onClick={()=>setAbout(false)}><X size={20}/></button><div className="eyebrow">THE JUDGMENT BETWEEN INSTRUCTION AND ACTION</div><h2 id="about-title">Some knowledge lives<br/>in the doing.</h2><p>“Remove the wash without disturbing the pellet” leaves much unsaid: where the pellet is, what the camera can see, which approach fits, and when to stop.</p><p>TACIT makes those decisions inspectable. It connects my experience isolating RNA at the bench and designing physical objects in 3D to a question in laboratory automation: what evidence makes an action executable?</p><div className="about-rule"/><h3>What this model demonstrates</h3><p>Geometric access, conserved liquid volume, image-derived observations, uncertainty-aware decisions, and reproducible comparisons. The highlighted pellet envelope is an explanation; camera evidence is generated separately.</p><h3>Where its claims stop</h3><p>This is a synthetic, quasistatic research workbench. Pellet adhesion, near-tip fluid dynamics, RNA yield, and physical fixture fit require laboratory validation. The model does not predict biological success.</p><div className="about-links"><a href="/docs/methods.html" target="_blank" rel="noreferrer">Read the model dossier<ArrowUpRight size={15}/></a><a href="https://www.transfyr.ai/news/ai-robotics" target="_blank" rel="noreferrer">The execution-data connection<ArrowUpRight size={15}/></a></div><div className="about-signature"><span>Raaif Bokhari</span><span className="mono">{MODEL_VERSION}</span></div></section></div>}
 </div>;
}
